CC=gcc
CFLAGS=-std=c11 -Wall -Werror -Wextra -pedantic -g

io: io.c
	$(CC) -o io io.c $(CFLAGS)

puzzels: puzzels.c
	$(CC) -o puzzels puzzels.c $(CFLAGS)

fileexist: fileexist.c
	$(CC) -o fileexist fileexist.c $(CFLAGS)

fileecho: fileecho.c
	$(CC) -o fileecho fileecho.c $(CFLAGS)

noAshere: noAshere.c
	$(CC) -o noAshere noAshere.c $(CFLAGS)

filecopy: filecopy.c
	$(CC) -o filecopy filecopy.c $(CFLAGS)

caeser: caeser.c
	$(CC) -0 caeser caeser.c $(CFLAGS)