CC=gcc
CFLAGS=-std=c11 -Wall -Werror -Wextra -pedantic -g

mynameis: mynameis.c
	$(CC) -o mynameis mynameis.c $(CFLAGS)

repeatme: repeatme.c
	$(CC) -o repeatme repeatme.c $(CFLAGS)

noAs: noAs.c
	$(CC) -o noAs noAs.c $(CFLAGS)

roll: roll.c
	$(CC) -o roll roll.c $(CFLAGS)

rand: rand.c
	$(CC) -o rand rand.c $(CFLAGS)